# Generated by Django 5.0.1 on 2024-02-07 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterpriseNumber', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=320, null=True)),
                ('commercialDenomination', models.CharField(blank=True, max_length=320, null=True)),
                ('country', models.CharField(blank=True, default='Belgique', max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=22, null=True)),
                ('box', models.CharField(blank=True, max_length=20, null=True)),
                ('extraAddressInfo', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('establishmentNumber', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(blank=True, max_length=320, null=True)),
                ('commercialDenomination', models.CharField(blank=True, max_length=320, null=True)),
                ('country', models.CharField(blank=True, default='Belgique', max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=22, null=True)),
                ('box', models.CharField(blank=True, max_length=20, null=True)),
                ('extraAddressInfo', models.CharField(blank=True, max_length=80, null=True)),
                ('enterprise', models.ForeignKey(db_column='enterpriseNumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='AlertAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('065c3492-56e2-7c54-8006-235d71db6d5f'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterpriseNumber', models.ForeignKey(blank=True, db_column='enterpriseNumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
                ('establishmentNumber', models.ForeignKey(blank=True, db_column='establishmentNumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.establishment')),
            ],
        ),
    ]
