# Generated by Django 5.0.3 on 2024-03-21 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6fa-70d5-8000-ec4f48598ea7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
