# Generated by Django 5.0.3 on 2024-03-21 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_alertaddress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a30b-7c97-8000-7db4d00c9592'), editable=False, primary_key=True, serialize=False),
        ),
    ]
