# Generated by Django 5.0.1 on 2024-02-09 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_attachment_id_alter_customerbilling_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaction',
            name='additionalContext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb41-769d-8000-e8e3e8834ee1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb35-7aa2-8000-a3cac6e0958b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb3a-7327-8000-30d1e81045c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdelivery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb37-7b9e-8000-e4a03f249f45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb3c-7890-8000-c66b3d408569'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb43-7aef-8001-d5259e7e1d6d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb46-703f-8000-81e87a3e0c62'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065c60c3-bb43-7aef-8000-ba00ac049ccf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
