# Generated by Django 5.0.3 on 2024-03-21 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderaction_additionalcontext_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFinancial',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('065fc0cb-d6f1-7dab-8000-f419dc0c2a8c'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('bankDuration', models.IntegerField(choices=[(2, 'Two Years'), (3, 'Three Years'), (4, 'Four Years'), (5, 'Five Years')], default=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6f1-7dab-8001-4f504c0a2a90'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6ed-7c26-8000-46a155c8bb0c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6ed-7c26-8002-14e939955ffd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdelivery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6ed-7c26-8001-c2e40828e090'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6ed-7c26-8003-c98ea3d63667'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6f5-7f56-8001-0ee172e52eae'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6f5-7f56-8002-3720be678297'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0cb-d6f5-7f56-8000-345f19f12f6f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
