# Generated by Django 5.0.3 on 2024-03-21 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_customerfinancial_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a302-7f51-8001-8cb958f6efd0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbilling',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a2fa-7c40-8000-f63e1d8620e6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a2fe-7dd7-8001-40952f47a58f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdelivery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a2fe-7dd7-8000-26a4f8ca9bf1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerfinancial',
            name='bankDuration',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (2, 'Two Years'), (3, 'Three Years'), (4, 'Four Years'), (5, 'Five Years')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerfinancial',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a302-7f51-8000-aa70c657ebc8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a2fe-7dd7-8002-292c0163c964'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a307-70dc-8000-2169ef99be9f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a307-70dc-8001-d52b4f8b72e9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065fc0d4-a302-7f51-8002-b66e14c2df92'), editable=False, primary_key=True, serialize=False),
        ),
    ]
